language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bcetinturk/docker-react-travis -f Dockerfile.dev .

script:
    - docker run -e CI=true bcetinturk/docker-react-travis npm run test